### ISSUE TITLE
question: why native implementation instead of foreign calls?

### ISSUE THREAD

**Issue by ghorn** [peddie/ghc-inverse-hyperbolic#2]
You foreign import `libm` in order to compare it to the native implementation. Wouldn't it be more efficient if the `libm` foreign call was the default and the native implementation was the test?

**Comment by peddie** [comment]
Neither of these is a default.  The reason I wrote a native one is because I don't know what's involved with GHC calling the system math library on arbitrary platforms; these implementations should be portable.
